#define SYS_printword       (-1)
#define SYS_read             0
#define SYS_write            1
#define SYS_fstat            5
#define SYS_brk              12
#define SYS_access           32
#define SYS_execve           59
#define SYS_exit             60
#define SYS_uname            63
#define SYS_readlink         89
#define SYS_arch_prctl       158
#define SYS_exit_group       231
